name: CI

on:
  workflow_dispatch:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v7
        with:
          node-version: latest
      - run: npm ci

      - run: npx vp check
